import { AnyRecord } from '../../../globalInterface';

export const recordsChart: AnyRecord[] = [
  {
    _id: '1',
    userId: '123-456-789',
    shortName: 'Uber from work to home',
    typeOfRecord: 'expense',
    description: 'Paying Uber to go to from work to home',
    amount: 15.49,
    amountFormatted: '$15.49',
    date: new Date('2024-08-20T12:08:00'),
    fullDate: 'Aug 20',
    formattedTime: '12:08pm',
    category: {
      _id: '1',
      __v: 0,
      categoryName: 'Transportation',
      icon: 'transportation',
      subCategories: ['Gas/Fuel', 'Uber/Didi'],
    },
    subCategory: 'Uber/Didi',
    tag: [],
    indebtedPeople: [],
    account: '5678',
    budgets: [],
    isPaid: false,
    linkedBudgets: [],
  },
  {
    _id: '3',
    userId: '123-456-789',
    shortName: 'Buy groceries',
    typeOfRecord: 'expense',
    description: 'Buy groceries',
    amount: 8.90,
    amountFormatted: '$8.90',
    date: new Date('2024-08-20T12:15:00'),
    fullDate: 'Aug 20',
    formattedTime: '12:15pm',
    category: {
      _id: '1',
      __v: 0,
      categoryName: 'Food and Drink',
      icon: 'foodAndDrink',
      subCategories: ['Bar', 'Groceries'],
    },
    subCategory: 'Groceries',
    tag: [],
    indebtedPeople: [],
    account: '5678',
    budgets: [],
    isPaid: false,
    linkedBudgets: [],
  },
  {
    _id: '2',
    userId: '123-456-789',
    shortName: 'Uber from home to work',
    typeOfRecord: 'expense',
    description: 'Paying Uber to go to from home to work',
    amount: 17.89,
    amountFormatted: '$17.89',
    date: new Date('2024-08-05T20:15:00'),
    fullDate: 'Aug 05',
    formattedTime: '20:15pm',
    category: {
      _id: '1',
      __v: 0,
      categoryName: 'Transportation',
      icon: 'transportation',
      subCategories: ['Gas/Fuel', 'Uber/Didi'],
    },
    subCategory: 'Uber/Didi',
    tag: [],
    indebtedPeople: [],
    account: '5678',
    budgets: [],
    isPaid: false,
    linkedBudgets: [],
  },
];
